# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/scan2d.ui'
#
# Created: Thu Nov 11 01:06:37 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Panel(object):
    def setupUi(self, Panel):
        Panel.setObjectName("Panel")
        Panel.resize(549, 646)
        self.gridLayout = QtGui.QGridLayout(Panel)
        self.gridLayout.setObjectName("gridLayout")
        self.plot = RasterPlot(Panel)
        self.plot.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plot.setFrameShadow(QtGui.QFrame.Raised)
        self.plot.setObjectName("plot")
        self.gridLayout.addWidget(self.plot, 3, 0, 1, 8)
        self.label = QtGui.QLabel(Panel)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.xstart = QtGui.QDoubleSpinBox(Panel)
        self.xstart.setMinimum(-100.0)
        self.xstart.setMaximum(100.0)
        self.xstart.setProperty("value", -10.0)
        self.xstart.setObjectName("xstart")
        self.gridLayout.addWidget(self.xstart, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Panel)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.xstop = QtGui.QDoubleSpinBox(Panel)
        self.xstop.setMinimum(-100.0)
        self.xstop.setMaximum(100.0)
        self.xstop.setProperty("value", 10.0)
        self.xstop.setObjectName("xstop")
        self.gridLayout.addWidget(self.xstop, 4, 3, 1, 1)
        self.label_6 = QtGui.QLabel(Panel)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 4, 1, 1)
        self.label_7 = QtGui.QLabel(Panel)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 6, 1, 1)
        self.pxtime = QtGui.QSpinBox(Panel)
        self.pxtime.setMinimum(1)
        self.pxtime.setObjectName("pxtime")
        self.gridLayout.addWidget(self.pxtime, 4, 7, 1, 1)
        self.label_2 = QtGui.QLabel(Panel)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.ystart = QtGui.QDoubleSpinBox(Panel)
        self.ystart.setMinimum(-100.0)
        self.ystart.setMaximum(100.0)
        self.ystart.setProperty("value", -10.0)
        self.ystart.setObjectName("ystart")
        self.gridLayout.addWidget(self.ystart, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Panel)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 2, 1, 1)
        self.ystop = QtGui.QDoubleSpinBox(Panel)
        self.ystop.setMinimum(-100.0)
        self.ystop.setMaximum(100.0)
        self.ystop.setProperty("value", 10.0)
        self.ystop.setObjectName("ystop")
        self.gridLayout.addWidget(self.ystop, 5, 3, 1, 1)
        self.label_5 = QtGui.QLabel(Panel)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 4, 1, 1)
        self.do_scan = QtGui.QPushButton(Panel)
        self.do_scan.setObjectName("do_scan")
        self.gridLayout.addWidget(self.do_scan, 5, 6, 1, 2)
        self.do_zoom = QtGui.QPushButton(Panel)
        self.do_zoom.setObjectName("do_zoom")
        self.gridLayout.addWidget(self.do_zoom, 2, 7, 1, 1)
        self.label_8 = QtGui.QLabel(Panel)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 4, 1, 2)
        self.zoomsize = QtGui.QDoubleSpinBox(Panel)
        self.zoomsize.setMinimum(1.0)
        self.zoomsize.setProperty("value", 20.0)
        self.zoomsize.setObjectName("zoomsize")
        self.gridLayout.addWidget(self.zoomsize, 2, 6, 1, 1)
        self.xsteps = QtGui.QSpinBox(Panel)
        self.xsteps.setMinimum(11)
        self.xsteps.setMaximum(1001)
        self.xsteps.setProperty("value", 101)
        self.xsteps.setObjectName("xsteps")
        self.gridLayout.addWidget(self.xsteps, 4, 5, 1, 1)
        self.ysteps = QtGui.QSpinBox(Panel)
        self.ysteps.setMinimum(11)
        self.ysteps.setMaximum(1001)
        self.ysteps.setProperty("value", 101)
        self.ysteps.setObjectName("ysteps")
        self.gridLayout.addWidget(self.ysteps, 5, 5, 1, 1)
        self.label.setBuddy(self.xstart)
        self.label_3.setBuddy(self.xstop)
        self.label_6.setBuddy(self.xsteps)
        self.label_7.setBuddy(self.pxtime)
        self.label_2.setBuddy(self.ystart)
        self.label_4.setBuddy(self.ystop)
        self.label_5.setBuddy(self.ysteps)
        self.label_8.setBuddy(self.zoomsize)

        self.retranslateUi(Panel)
        QtCore.QObject.connect(self.do_scan, QtCore.SIGNAL("clicked()"), Panel.start_scan)
        QtCore.QObject.connect(self.do_zoom, QtCore.SIGNAL("clicked()"), Panel.zoom)
        QtCore.QMetaObject.connectSlotsByName(Panel)

    def retranslateUi(self, Panel):
        Panel.setWindowTitle(QtGui.QApplication.translate("Panel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Panel", "x start [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Panel", "x stop [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Panel", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Panel", "px time[ms]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Panel", "y start [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Panel", "y stop [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Panel", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.do_scan.setText(QtGui.QApplication.translate("Panel", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.do_zoom.setText(QtGui.QApplication.translate("Panel", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Panel", "zoom size [um]", None, QtGui.QApplication.UnicodeUTF8))

from plot.raster_plot import RasterPlot
